In [2]:
def to_lowercase(text):
    return text.lower()

# Contoh penggunaan
sample_text = "AKU BOCIL GANTENG ."
print(to_lowercase(sample_text))


aku bocil ganteng .


In [3]:
import string

def remove_punctuation(text):
    return text.translate(str.maketrans('', '', string.punctuation))

# Contoh penggunaan
sample_text = "UGH !!! Kaget"
print(remove_punctuation(sample_text))


UGH  Kaget


In [4]:
import re

def remove_numbers(text):
    return re.sub(r'\d+', '', text)

# Contoh penggunaan
sample_text = " 1 2 kucing kelabu nenek tua berambut abu - abu"
print(remove_numbers(sample_text))


   kucing kelabu nenek tua berambut abu - abu


In [6]:
from nltk.tokenize import word_tokenize
import nltk

nltk.download('punkt_tab')

def tokenize(text):
    return word_tokenize(text)

# Contoh penggunaan
sample_text = "Ular melingkar dipagar berputar - putar"
print(tokenize(sample_text))


['Ular', 'melingkar', 'dipagar', 'berputar', '-', 'putar']


[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


In [7]:
from nltk.corpus import stopwords

nltk.download('stopwords')

def remove_stopwords(words):
    stop_words = set(stopwords.words('english'))
    return [word for word in words if word not in stop_words]

# Contoh penggunaan
sample_text = "Duh lagi mental health nich which is butuh healing"
tokenized_text = tokenize(sample_text)
print(remove_stopwords(tokenized_text))


['Duh', 'lagi', 'mental', 'health', 'nich', 'butuh', 'healing']


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [11]:
from nltk.stem import PorterStemmer

def stem_words(words):
    ps = PorterStemmer()
    return [ps.stem(word) for word in words]

# Contoh penggunaan
sample_text = "Aku membutuhkan medkit,so thx"
tokenized_text = tokenize(sample_text)
filtered_words = remove_stopwords(tokenized_text)
print(stem_words(filtered_words))


['aku', 'membutuhkan', 'medkit', ',', 'thx']


In [13]:
sentence1 = "Sara sarang diskriminasi"
sentence2 = "Orang kulit hitam mendapat diskriminasi di Amerika"
sentence3 = "Di amerika orang kulit hitam mengadakan black lives matter"

In [14]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
docs = [sentence1, sentence2, sentence3]
print(docs)

['Sara sarang diskriminasi', 'Orang kulit hitam mendapat diskriminasi di Amerika', 'Di amerika orang kulit hitam mengadakan black lives matter']


In [15]:
#Mendefinisikan dan menyesuaikan count vectorizer pada dokumen.

vec = CountVectorizer()
X = vec.fit_transform(docs)
#Mengonversi vektor pada DataFrame menggunakan pandas

df = pd.DataFrame(X.toarray(),
    columns=vec.get_feature_names_out())
df.head()

amerika  black  di  diskriminasi  hitam  kulit  lives  matter  mendapat  \
0        0      0   0             1      0      0      0       0         0   
1        1      0   1             1      1      1      0       0         1   
2        1      1   1             0      1      1      1       1         0   

   mengadakan  orang  sara  sarang  
0           0      0     1       1  
1           0      1     0       0  
2           1      1     0       0

In [16]:
import numpy as np
from collections import Counter
from math import log

# Tiga dokumen dalam korpus
documents = [
    "Hera menghancurkan Asgard",
    "Thor menciptakan ragnarok untuk mencegah Hera menghancurkan Asgard"
    ]

# Preprocessing: Lowercasing and tokenizing
tokenized_documents = [doc.lower().split() for doc in documents]

# Menghitung TF
def compute_tf(tokenized_doc):
    tf_dict = {}
    term_count = Counter(tokenized_doc)
    total_terms = len(tokenized_doc)
    for term, count in term_count.items():
        tf_dict[term] = count / total_terms
    return tf_dict

tf_list = [compute_tf(doc) for doc in tokenized_documents]

print("Term Frequency (TF):")
for idx, tf in enumerate(tf_list):
    print(f"Document {idx + 1} TF:")
    for term, score in tf.items():
        print(f"    {term}: {score:.4f}")


Term Frequency (TF):
Document 1 TF:
    hera: 0.3333
    menghancurkan: 0.3333
    asgard: 0.3333
Document 2 TF:
    thor: 0.1250
    menciptakan: 0.1250
    ragnarok: 0.1250
    untuk: 0.1250
    mencegah: 0.1250
    hera: 0.1250
    menghancurkan: 0.1250
    asgard: 0.1250


In [17]:
# Menghitung IDF
def compute_idf(tokenized_docs):
    idf_dict = {}
    total_docs = len(tokenized_docs)
    all_terms = set(term for doc in tokenized_docs for term in doc)
    for term in all_terms:
        doc_containing_term = sum(1 for doc in tokenized_docs if term in doc)
        idf_dict[term] = log(total_docs / (1 + doc_containing_term)) + 1
    return idf_dict

idf_dict = compute_idf(tokenized_documents)

print("\nInverse Document Frequency (IDF):")
for term, score in idf_dict.items():
    print(f"    {term}: {score:.4f}")



Inverse Document Frequency (IDF):
    asgard: 0.5945
    menghancurkan: 0.5945
    menciptakan: 1.0000
    ragnarok: 1.0000
    mencegah: 1.0000
    hera: 0.5945
    untuk: 1.0000
    thor: 1.0000


In [18]:
# Menghitung TF-IDF
def compute_tfidf(tf_list, idf_dict):
    tfidf_list = []
    for tf in tf_list:
        tfidf_dict = {}
        for term, tf_value in tf.items():
            tfidf_dict[term] = tf_value * idf_dict.get(term, 0)
        tfidf_list.append(tfidf_dict)
    return tfidf_list

tfidf_list = compute_tfidf(tf_list, idf_dict)

print("\nTF-IDF:")
for idx, tfidf in enumerate(tfidf_list):
    print(f"Document {idx + 1} TF-IDF:")
    for term, score in tfidf.items():
        print(f"    {term}: {score:.4f}")


TF-IDF:
Document 1 TF-IDF:
    hera: 0.1982
    menghancurkan: 0.1982
    asgard: 0.1982
Document 2 TF-IDF:
    thor: 0.1250
    menciptakan: 0.1250
    ragnarok: 0.1250
    untuk: 0.1250
    mencegah: 0.1250
    hera: 0.0743
    menghancurkan: 0.0743
    asgard: 0.0743


In [21]:
pip install --force-reinstall --no-cache-dir gensim

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 5.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.6/60.6 kB 100.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 26.7/26.7 MB 262.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.3/18.3 MB 263.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 38.6/38.6 MB 214.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.7/61.7 kB 188.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 83.2/83.2 kB 112.9 MB/s eta 0:00:00
  Attempting uninstall: wrapt
    Found existing installation: wrapt 1.17.2
    Uninstalling wrapt-1.17.2:
      Successfully uninstalled wrapt-1.17.2
  Attempting uninstall: numpy
    Found existing installation: numpy 1.26.4
    Uninstalling numpy-1.26.4:
      Successfully uninstalled numpy-1.26.4
  Attempting uninstall: smart-open
    Found existing installation: smart-open 7.1.0
    Uninstalling smart-open-7.1.0:
      Successfull

In [2]:
from gensim.models import Word2Vec
import numpy as np

corpus = [
    'Iam the bones of my sword.',
    'Steel is my body and fire is my blood.',
    'I created over thousand blade.',
    'Unknown to live and unknown to death',
    'So as i pray unlimited blade works'
]

sentences = [doc.split() for doc in corpus]
model = Word2Vec(sentences, vector_size=100, window=5, min_count=1, workers=4)

def document_vector(doc):
    return np.mean([model.wv[word] for word in doc.split() if word in model.wv], axis=0)

doc_vectors = [document_vector(doc) for doc in corpus]
print(doc_vectors)


[array([ 1.5627211e-03, -1.1602900e-03, -5.1071402e-06,  6.7668105e-03,
       -2.5523729e-03, -4.8593534e-04,  4.6453779e-03,  1.1680244e-04,
       -3.4880992e-03, -9.8174333e-04,  2.3950818e-03, -1.7119929e-03,
        2.7487848e-03,  3.3323476e-03, -2.1294125e-03,  2.7878706e-03,
        4.0636286e-03, -1.1773941e-03, -1.9629945e-03, -6.6884183e-03,
        3.1574790e-03,  3.8410861e-03,  4.5802752e-03, -1.0814277e-03,
        2.5968598e-03, -5.8973831e-04, -3.1036965e-03,  1.3388920e-03,
       -2.1771721e-03, -1.2336334e-03,  2.8191637e-03,  2.3639072e-03,
        4.5969966e-03, -1.1092502e-04, -4.3496639e-03,  1.7287437e-03,
       -7.2378200e-05, -8.7980129e-04, -2.4487821e-03, -3.1367058e-03,
        5.1215367e-05,  2.6666916e-03, -1.7266670e-04, -3.6295217e-03,
        2.2928494e-03,  1.4156488e-03, -5.1053343e-03,  1.7396617e-04,
        1.7904291e-03,  3.3844991e-03, -4.0396047e-03,  4.3493346e-04,
       -1.9491910e-03, -2.6039252e-04,  1.0006939e-03, -3.2436412e-03,
     

In [3]:
!pip install numpy pandas scikit-learn


Klasifikasi teks dengan Machine Learning.
This dataset is a collection newsgroup documents. The 20 newsgroups collection has become a popular data set for experiments in text applications of machine learning techniques, such as text classification and text clustering.


In [10]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import make_pipeline
from sklearn import metrics
import pandas as pd


# 1. Mengumpulkan data
df = pd.read_csv("ulasan.csv")

# 2. Menyiapkan fitur dan label
X = df['ulasan']
y = df['score']

# 3. Membagi data menjadi training dan testing set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

# 4. Melatih model
# Membuat pipeline yang mencakup TfidfVectorizer dan MultinomialNB
model = make_pipeline(TfidfVectorizer(), MultinomialNB())

# Melatih model menggunakan training set
model.fit(X_train, y_train)

# 5. Mengevaluasi model
# Prediksi pada testing set
y_pred = model.predict(X_test)

# Evaluasi kinerja model
print(f"Accuracy: {metrics.accuracy_score(y_test, y_pred):.3f}")
print("Classification Report:")
print(metrics.classification_report(y_test, y_pred, zero_division=0))
# Confusion Matrix
print("Confusion Matrix:")
print(metrics.confusion_matrix(y_test, y_pred))


Accuracy: 0.656
Classification Report:
              precision    recall  f1-score   support

           1       0.60      1.00      0.75       116
           2       0.00      0.00      0.00        19
           3       0.00      0.00      0.00        16
           4       0.00      0.00      0.00        16
           5       0.83      0.58      0.68        83

    accuracy                           0.66       250
   macro avg       0.29      0.32      0.29       250
weighted avg       0.56      0.66      0.58       250

Confusion Matrix:
[[116   0   0   0   0]
 [ 18   0   0   0   1]
 [ 14   0   0   0   2]
 [  9   0   0   0   7]
 [ 35   0   0   0  48]]
